### ISSUE TITLE
Spams console with errors

### ISSUE THREAD

**Issue by yavko** [LaserSlime/AntiHealthIndicator#1]
The errors look like
```
- [Sat 17:36:38 ERROR Minecraft] [AntiHealthIndicator] Unhandled exception number 128 occured in onPacketSending(PacketEvent) for AntiHealthIndicator
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "entity" is null
    at antihealthindicator-1.1.0.jar//de.laserslime.antihealthindicator.packetadapters.EntityMetadataAdapter.filter(EntityMetadataAdapter.java:45)
    at antihealthindicator-1.1.0.jar//de.laserslime.antihealthindicator.packetadapters.EntityMetadataAdapter.onPacketSending(EntityMetadataAdapter.java:38)
    at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
    at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
    at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535)
    at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516)
    at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346)
    at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308)
    at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:436)
    at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:72)
    at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:376)
    at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:346)
    at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
    at ProtocolLib.jar//com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
    at net.mine
```
and 

```
- [Sat 17:41:35 ERROR Minecraft] [AntiHealthIndicator] Unhandled exception number 256 occured in onPacketSending(PacketEvent) for AntiHealthIndicator
java.lang.NullPointerException
```

**Comment by LaserSlime** [comment]
What server version are you using?

**Comment by yavko** [comment]
> What server version are you using?

1.18.2
https://github.com/Pearl-Project/Pearl

**Comment by LaserSlime** [comment]
Still can't reproduce. Are you using the latest version of ProtocolLib?

**Comment by yavko** [comment]
> Still can't reproduce. Are you using the latest version of ProtocolLib?

Yeah

**Comment by yavko** [comment]
Should i give a list of plugins?

**Comment by LaserSlime** [comment]
Yeah sure. Also make sure you're using the latest version of ViaVersion/ViaBackwards if you're using that.

**Comment by yavko** [comment]
```
Plugins (38): 3DItems, AdvancedHelp, AntiHealthIndicator, AppleCoreSpigot, AureliumMobs, AureliumSkills, BloodInMinecraft, ChatBubbles, Chunky, ChunkyBorder, CustomCommands, DiscordSRV, DiscordSRV-Staff-Chat, DiscordSRVUtils, DoorsReloaded, DropHeads, DualWield, emotecraft*, HolographicDisplays, Informant-Spigot*, InteractiveChat, InteractiveChatDiscordSrvAddon, KaBoom, LifeSteal, LuckPerms, MoreOres, PlaceholderAPI, PlugManX (PlugMan), ProtocolLib, ServerListPlus*, SimpleScore, SuperVanish, SwingThroughGrass, TabList, TimePauser, UnexpectedSpawn, Vault, VaultChatFormatter*
```

**Comment by LaserSlime** [comment]
Ok I'm just gonna guess that it's HolographicDisplays or some similar plugin that spawns fake entities causing the issue. Simple check should fix it.

**Comment by yavko** [comment]
> Ok I'm just gonna guess that it's HolographicDisplays or some similar plugin that spawns fake entities causing the issue. Simple check should fix it.

Okay
