### ISSUE TITLE
Plugin not loading

### ISSUE THREAD

**Issue by IceWaffles** [LaserSlime/AntiHealthIndicator#3]
`[10:58:27 ERROR]: Error occurred while enabling AntiHealthIndicator v1.2.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "de.laserslime.antihealthindicator.util.Version.getBukkitVersion()" is null
        at de.laserslime.antihealthindicator.util.Version.getServerVersion(Version.java:29) ~[antihealthindicator-1.2.0.jar:?]
        at de.laserslime.antihealthindicator.main.Main.onEnable(Main.java:24) ~[antihealthindicator-1.2.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[pufferfishplus-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[pufferfishplus-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:548) ~[pufferfishplus-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin() ~[pufferfishplus-1.19.2.jar:git-PufferfishPlus-13]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins() ~[pufferfishplus-1.19.2.jar:git-PufferfishPlus-13]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java) ~[pufferfishplus-1.19.2.jar:git-PufferfishPlus-13]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java) ~[pufferfishplus-1.19.2.jar:git-PufferfishPlus-13]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java) ~[pufferfishplus-1.19.2.jar:git-PufferfishPlus-13]
        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java) ~[pufferfishplus-1.19.2.jar:git-PufferfishPlus-13]
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java) ~[pufferfishplus-1.19.2.jar:git-PufferfishPlus-13`

**Comment by LaserSlime** [comment]
Fixed in 1.2.2
